version: '3.1'
services:
  server:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports: 
      - 3300:3000
    depends_on: 
      - mongo
    restart: always
    working_dir: /app
    expose:
      - "3000"
    links:
      - mongo

  mongo:
      image: mongo
      expose:
        - 27017
      ports: 
        - 27017:27017
      volumes:
        - ./data/db:/data/db
      restart: always
      logging:
        driver: none
      environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: 123456789